run:
    timeout: 5m

linters-settings:
    govet:
        disable:
            - fieldalignment
    gocyclo:
        min-complexity: 15
    dupl:
        threshold: 100
    goconst:
        min-len: 3
        min-occurrences: 5
    misspell:
        locale: US
    funlen:
        lines: 100
        statements: 50
    gocognit:
        min-complexity: 20

linters:
    disable-all: false
    disable:
        - gofmt
        - gofumpt
        - goimports

issues:
    exclude-use-default: false
    max-issues-per-linter: 0
    max-same-issues: 0
    exclude-rules:
        - path: _test\.go
          linters:
              - funlen
              - dupl
              - gocognit
              - gocyclo
